package com.sha.shopping_books.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@AllArgsConstructor
@NoArgsConstructor
@Builder
@Getter
@Setter
@DynamoDBTable(tableName = "book")
public class Book {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String author;

    @DynamoDBAttribute
    private String price;

    @DynamoDBAttribute
    private String photo;

    @DynamoDBAttribute
    private String createdBy;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private Status status;

    public enum Status{
        PUBLIC,PRIVATE
    }

}
