package com.sha.shopping_books.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.time.LocalDateTime;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@DynamoDBTable(tableName = "payment")
public class Payment {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime createdDate;

    @DynamoDBAttribute
    private String bookId;

    @DynamoDBAttribute
    private String userId;

    @DynamoDBAttribute
    private String count;

    @DynamoDBAttribute
    private String photo;

    @DynamoDBAttribute
    private String price;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private PaymentBy paymentBy;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private Status status;


    public enum PaymentBy {
        KBZ, CB, AYA
    }

    public enum Status{
        IN_PROGRESS,DONE,CANCEL
    }
}
